### PR TITLE
Side Navigation:  initial selection persist issue fix

### LINKED ISSUE #2147: Side Navigation Initial Selection Persisting
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

When a side navigation item is selected on creation (`selected="true"`), a click will not clear the initial selection on the first time resulting in two items selected as seen in the picture:

image

Expected Behavior: Only the newly 'clicked' item is selected.

Reproduction:

```html
<html>

<head>
    <script src="test.bundle.js" type="module"></script>
</head>

<body>
    <div id="defaultTemplate" style="height: 100%; display: flex; flex-flow: column">
        <div style="width: 100%;align-items: center;height: 56px;box-shadow: 0 0 2px var(--modus-secondary)!important">
            <modus-navbar show-apps-menu show-help show-main-menu>
            </modus-navbar>
        </div>

        <div id="container"
            style="display:flex; min-height:500px; overflow-y: auto; position: relative;box-shadow: 0 0 2px var(--modus-secondary)!important; height: 100%;">
            <modus-side-navigation max-width="300px" id="sideNav" target-content="#defaultTemplate #panelcontent" style="height: 100%;">
                <modus-side-navigation-item id="home-menu" label="Home page" selected="true">
                    <svg slot="menu-icon" xmlns="http://www.w3.org/2000/svg" fill="currentColor" height="24" width="24"
                        viewBox="0 0 32 32">
                        <style>
                            .st1 {
                                stroke: #000;
                                stroke-miterlimit: 10;
                            }
                        </style>
                        <path
                            d="M30.707 15.293 26 10.586V5a1 1 0 0 0-1-1h-2a1 1 0 0 0-1 1v1.586l-4.293-4.293a1 1 0 0 0-1.414 0l-13 13A1 1 0 0 0 4 17h3v12a1 1 0 0 0 1 1h5a1 1 0 0 0 1-1v-7h6v7a1 1 0 0 0 1 1h5a1 1 0 0 0 1-1V17h3a1 1 0 0 0 .707-1.707z" />
                    </svg>
                </modus-side-navigation-item>
                <modus-side-navigation-item id="usage-menu" label="Usage">
                    <svg slot="menu-icon" xmlns="http://www.w3.org/2000/svg" fill="currentColor" height="24" width="24"
                        viewBox="0 0 32 32">
                        <g>
                            <path
                                d="M30 23v6c0 .55-.45 1-1 1h-6c-.55 0-1-.45-1-1v-6c0-.55.45-1 1-1h2v-5h-8v5h2c.55 0 1 .45 1 1v6c0 .55-.45 1-1 1h-6c-.55 0-1-.45-1-1v-6c0-.55.45-1 1-1h2v-5H7v5h2c.55 0 1 .45 1 1v6c0 .55-.45 1-1 1H3c-.55 0-1-.45-1-1v-6c0-.55.45-1 1-1h2v-6c0-.55.45-1 1-1h9v-5h-2c-.55 0-1-.45-1-1V3c0-.55.45-1 1-1h6c.55 0 1 .45 1 1v6c0 .55-.45 1-1 1h-2v5h9c.55 0 1 .45 1 1v6h2c.55 0 1 .45 1 1z" />
                        </g>
                    </svg>
                </modus-side-navigation-item>
            </modus-side-navigation>

            <div id="panelcontent" style="padding:10px;">
            </div>
        </div>
    </div>

    <script>
        function addEventHandlers() {
          document.addEventListener('mainMenuClick', (e) => {
            const panel = document.querySelector('modus-side-navigation');
            panel.expanded = !panel.expanded;
          });
      
          Array.from(document.querySelectorAll('modus-side-navigation-item')).forEach(
            (c) => {
              c.addEventListener('sideNavItemClicked', function callbackfn(e) {
              });
            }
          );
        }
      
        addEventHandlers();
      </script>
</body>

</html>
```

### Reduced test cases

_No response_

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

0.16.0

### Priority

High

### What product/project are you using Modus Components for ?

ModusBlazor

### What is your team/division name ?

AECO

### Are you willing to contribute ?

None

### Are you using Modus Web Components in production ?

_No response_

### PR DESCRIPTION
**Pull request by prashanthr6383**
## Description

References 

Fixes #2147 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: stencil-workspace/src/components/modus-side-navigation/modus-side-navigation-item/modus-side-navigation-item.tsx [hunk 1]
```diff
@@ -165,6 +165,14 @@ export class ModusSideNavigationItem {
   handleClick(): void {
     if (this.disabled) return;
 
+    const allItems = this.element.parentElement?.querySelectorAll('modus-side-navigation-item');
```
Comment (saravananrmsmy) [inline stencil-workspace/src/components/modus-side-navigation/modus-side-navigation-item/modus-side-navigation-item.tsx:168]: Do we need to add test case for the scenario ?

Comment (prashanthr6383) [reply stencil-workspace/src/components/modus-side-navigation/modus-side-navigation-item/modus-side-navigation-item.tsx:168]: @saravananrmsmy  yes. I have added now

**Review by jewel-shajan — COMMENTED** [review]
Testing completed after changes.

File: stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.e2e.ts [hunk 2]
```diff
@@ -374,3 +374,35 @@ describe('modus-side-navigation-item', () => {
     expect(focusEvent).toHaveReceivedEvent();
   });
 });
+
+it('should not get selected when other item is clicked', async () => {
+  const page = await newE2EPage();
+  await page.setContent(`
+  <modus-side-navigation>
+    <modus-side-navigation-item id="Test" label="Test" selected>
+    <svg slot="menu-icon" fill="currentColor" height="24" width="24" viewBox="0 0 32 32">
```
Comment (saravananrmsmy) [inline stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.e2e.ts:383]: Do we need to have the paths of the svg or just the placeholder is enough ?

Comment (prashanthr6383) [reply stencil-workspace/src/components/modus-side-navigation/modus-side-navigation.e2e.ts]: Hi @saravananrmsmy for this scenario we don't require paths so I have updated the same in code.

**Review by saravananrmsmy — APPROVED** [review]
