### PR TITLE
FileDropzone  : Fix reset button loading time

### LINKED ISSUE #2924: Fix File Dropzone reset button loading time
**Issue Summary**
The reset button in the file dropzone is not loading initially, which causes test cases to fail. This causes test cases to fail randomly as button does not load every time. The fix involves loading the button from the start and controlling its visibility based on error conditions. 

**Steps to Reproduce**

- Open the file dropzone component.
- Observe the initial loading state and check when the reset button appears.
- Trigger an error condition (e.g., invalid file upload).
- Verify the visibility of the reset button in response to the error.

**Expected Result**
The reset button should be visible from the initial loading of the file dropzone. It should be shown or hidden based on the error state:

**Observed Result**
Currently, the reset button loads after a delay, which causes test cases that check for its visibility to fail.

### PR DESCRIPTION
**Pull request by ElishaSamPeterPrabhu**
## Description

- Fixes the flaky test
- Fixes lint errors

References 
Fixes #2924 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.tsx [hunk 1]
```diff
@@ -229,7 +229,7 @@ export class ModusFileDropzone {
                 </div>
               ))}
             {this.error && (
-              <div class="error-messages" role="alert">
+              <div class={`error-messages ${this.error ? '' : 'hidden'}`} role="alert">
```
Comment (prashanth-offcl) [inline stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.tsx:232]: @ElishaSamPeterPrabhu Can we revert this change?

Comment (ElishaSamPeterPrabhu) [reply stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.tsx]: Reverted

**Review by prashanth-offcl — APPROVED** [review]
