### PR TITLE
Toast: Add prop to retain element on dismiss

### LINKED ISSUE #2835: Toast: error on dismiss [React wrapper]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

When dismissing the toast (either by clicking the x button or letting the timer expire) I'm getting the following error:
`NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`
I'm using the react wrapper. This doesn't seems to be happening in storybook.

This is how I'm using the toast:
```
{toast && (
        <ModusToast type={toast.type} showIcon onDismissClick={() => setToast(null)}>
          {toast.message}
        </ModusToast>
)}
```
### Reduced test cases

_No response_

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

0.37.0-react18

### Priority

High

### What product/project are you using Modus Components for ?

Trimble DVIR

### What is your team/division name ?

Camaleão/Transportation

### Are you willing to contribute ?

No

### Are you using Modus Web Components in production ?

_No response_

### PR DESCRIPTION
**Pull request by ElishaSamPeterPrabhu**
## Description

- Add `retainELement ` prop to not stop the toast component from getting removed from the dom
References 
Fixes #2835 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: stencil-workspace/src/components/modus-toast/modus-toast.tsx [hunk 1]
```diff
@@ -70,7 +73,9 @@ export class ModusToast {
 
   dismissElement() {
     this.dismissClick.emit();
-    this.el.remove();
+    if (!this.retainElement) {
```
Comment (prashanth-offcl) [inline stencil-workspace/src/components/modus-toast/modus-toast.tsx:76]: @ElishaSamPeterPrabhu can you add tests for this?

Comment (ElishaSamPeterPrabhu) [reply stencil-workspace/src/components/modus-toast/modus-toast.tsx:76]: Added test cases

File: stencil-workspace/src/components/modus-toast/modus-toast.e2e.ts [hunk 2]
```diff
@@ -110,4 +110,30 @@ describe('modus-toast', () => {
     await page.waitForTimeout(10000);
     expect(dismissClick).toHaveReceivedEvent();
   });
+
+  it('removes the element from the DOM when retainElement is true', async () => {
```
Comment (prashanth-offcl) [inline stencil-workspace/src/components/modus-toast/modus-toast.e2e.ts:114]: @ElishaSamPeterPrabhu Looks like the test description is incorrect, please check.

Comment (ElishaSamPeterPrabhu) [reply stencil-workspace/src/components/modus-toast/modus-toast.e2e.ts]: Modified the description

**Review by prashanth-offcl — APPROVED** [review]
