### PR TITLE
Table: expandable rows not working in single row table

### LINKED ISSUE #2903: Modus Table - Expandable rows not working in single row table
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

The expandable row feature of the modus table only works when the expandable row is not the last or only row in the table.

### Reduced test cases

- Open the [expandable rows storybook](https://modus-web-components.trimble.com/?path=/story/components-table--expandable-rows)
- Click the expand icon.
   - Row expands like expected.
- Remove all data expect for item 0.
- Click the expand icon.
   - Nothing happens.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

_No response_

### Priority

Medium

### What product/project are you using Modus Components for ?

Nova / Construction calculation platform UI

### What is your team/division name ?

ACDC

### Are you willing to contribute ?

No

### Are you using Modus Web Components in production ?

_No response_

### PR DESCRIPTION
**Pull request by prashanthr6383**
## Description

References 
Fixes #2903  

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

File: stencil-workspace/src/components/modus-table/modus-table.tsx [hunk 1]
```diff
@@ -123,7 +123,11 @@ export class ModusTable {
     this.tableCore?.setState('pagination', {
       ...this.tableState.pagination,
       pageIndex: this.tableState.pagination.pageIndex,
-      pageSize: this.pagination ? this.tableState.pagination.pageSize : this.data.length,
+      pageSize: this.pagination
+        ? this.tableState.pagination.pageSize
+        : this.rowsExpandable
+          ? this.pageSizeList[0]
```
Comment (prashanthr6383) [inline stencil-workspace/src/components/modus-table/modus-table.tsx:129]: if rows expandable is enabled then default value of pageSizeList(10) will be set instead of the data.length so that the rows can be expanded

**Review by jewel-shajan — COMMENTED** [review]
Testing is complete, and everything is working as expected.

**Review by coliff — APPROVED** [review]

**Comment by coliff** [comment]
@prashanthr6383 can you please resolve the conflict. thanks!

**Comment by prashanthr6383** [comment]
> @prashanthr6383 can you please resolve the conflict. thanks!

okay.

**Review by coliff — APPROVED** [review]
